# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1396392558);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1396394385);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1396392678);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1396392438);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 307200);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140218140338");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20140218140338");
user_pref("browser.startup.homepage_override.mstone", "27.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4,\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1395784628806");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1396394349197");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1396394353318");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1396480753318");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1393601406393");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1393601417685");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1383699362877");
user_pref("datareporting.sessions.current.activeTicks", 56);
user_pref("datareporting.sessions.current.firstPaint", 9285);
user_pref("datareporting.sessions.current.main", 1338);
user_pref("datareporting.sessions.current.sessionRestored", 8878);
user_pref("datareporting.sessions.current.startTime", "1396392313847");
user_pref("datareporting.sessions.current.totalTime", 1693);
user_pref("datareporting.sessions.currentIndex", 24);
user_pref("datareporting.sessions.prunedIndex", 23);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 9);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"27.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"27.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 15);
user_pref("extensions.enabledAddons", "%7Bc45c406e-ab73-11d8-be73-000a95be3b12%7D:1.2.5,ubufox%40ubuntu.com:2.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:27.0.1");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140319.01");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1377021535000,\"rdfTime\":1375741724000}}},{\"name\":\"app-global\",\"addons\":{\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1392734107000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1395166780000,\"rdfTime\":1392733239000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1392734107000}}},{\"name\":\"app-profile\",\"addons\":{\"{c45c406e-ab73-11d8-be73-000a95be3b12}\":{\"descriptor\":\"/home/saasbook/.mozilla/firefox/k5rp140e.default/extensions/{c45c406e-ab73-11d8-be73-000a95be3b12}.xpi\",\"mtime\":1383699409000}}}]");
user_pref("extensions.lastAppVersion", "27.0.1");
user_pref("extensions.lastPlatformVersion", "27.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.webdeveloper.version", "1.2");
user_pref("gecko.buildID", "20140218140338");
user_pref("gecko.mstone", "27.0.1");
user_pref("idle.lastDailyNotification", 1396394609);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1396394349);
user_pref("places.history.expiration.transient_current_max_pages", 34605);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("spellchecker.dictionary", "en_GB");
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1395784678);
user_pref("toolkit.startup.last_success", 1396392315);
user_pref("toolkit.telemetry.previousBuildID", "20140218140338");
user_pref("urlclassifier.download_allow_table", "");
user_pref("urlclassifier.download_block_table", "");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1398376569);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
