#!/usr/bin/env bash

if [[ -s "/home/saasbook/.rvm/environments/ruby-1.9.3-p448" ]]
then
  source "/home/saasbook/.rvm/environments/ruby-1.9.3-p448"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/saasbook/.rvm/environments/ruby-1.9.3-p448'" >&2
  exit 1
fi
